version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
        - checkout
        - newman/newman-run:
            collection: ./tests/PostmanTrelloCollections.json
            environment: ./tests/TrelloEnv.json
workflows:
  version: 1
  workflow:
    jobs:
    - newman-collection-run